fund_rapi.url = "http://localhost:9090"
logout-other-users=true

exir.login.twoStepVerification{
    otpExpirationTime : 90
    maxNumberOfAttempts : 3
}

management.hosts += "127.0.0.1"
management.hosts += "172.30.21.0/24"
